planning_plugins:
  - ompl_interface/OMPLPlanner

request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision

response_adapters:
  - default_planning_response_adapters/AddTimeOptimalParameterization
  - default_planning_response_adapters/ValidateSolution
  - default_planning_response_adapters/DisplayMotionPath

totg:
  resample_dt: 0.01

planner_configs:

  RRTConnect:
    type: geometric::RRTConnect
    range: 1.0

  RRTstar:
    type: geometric::RRTstar
    range: 0.5
    goal_bias: 0.05
    delay_collision_checking: 1

  LazyPRMstar:
    type: geometric::LazyPRMstar

  RRT:
    type: geometric::RRT
    range: 0.5
    goal_bias: 0.05

manipulador:
  planner_configs:
    - RRTConnect
    - RRTstar
    - LazyPRMstar
    - RRT
  projection_evaluator: joints(joint1,joint2)
  longest_valid_segment_fraction: 0.0003
