<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rl6gdl_planning</name>
  <version>0.1.0</version>
  <description>
    Configuracion de OMPL y utilidades de verificacion para la linea base clasica
    del proyecto de planificacion de movimiento con aprendizaje por refuerzo
    para un manipulador de 6 GDL. Paquete de trabajo 3.9 de la EDT.
  </description>
  <maintainer email="caleb.camargo.s@uni.pe">Caleb Camargo</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>moveit_ros_move_group</exec_depend>
  <exec_depend>moveit_planners_ompl</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>rl6gdl_e6_description</exec_depend>
  <exec_depend>ur_description</exec_depend>
  <exec_depend>ur_moveit_config</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>moveit_msgs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
